# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f26fba5ff56de1a3673a9ce7f924d053f595244a69b2fd9912714c2121623a233a7e5d28b2a80e33dd85da91e38791234ca2e086f295ae13907d495d1ba522bc

test:
  secret_key_base: 9159c9e51b9b405ecc55150a819bda2eb1424d31c84c92969ceab73e95fd23286cbd6e8b2f6af48dd8ed51c6e84897d3268dd02e42496d28ed9bf3cbb999e1d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
